sound: minecraft:block.composter.ready
# played sound when quick harvest

feature:
  player: vanilla
  # quick harvest by right-click:
  #   default - harvested items will automatically transfer to inventory
  #   vanilla - harvested items will just drop on the ground
  #   disabled - completely disable this feature

  dispenser: yes
  # quick harvest by dispenser (yes/no)

  hoe-dura-cost: yes
  # does harvesting consume the durability of the hoe (yes/no)

targets:
  - minecraft:wheat
  - minecraft:beetroots
  - minecraft:potatoes
  - minecraft:carrots
  - minecraft:nether_wart
  - minecraft:cocoa
